### PR TITLE
Split header file from MemoryScan.cpp

### PR DESCRIPTION
**Pull request by shashwatj07**

### CODE REVIEW

**Comment by yatendra1999** [comment]
You should leave only the prototypes in the header file and provide their actual definitions inside the cpp file. This is widely accepted norm and we should also follow this

**Review by yatendra1999 — CHANGES_REQUESTED** [review]
Only the function prototypes should remain inside the header file and the definitions must be in the main cpp file.

**Comment by shashwatj07** [comment]
@yatendra1999 ping

**Review by yatendra1999 — APPROVED** [review]
Ready to merge.

**Pull request merged**
